#!/bin/sh
# Run the reviewer benchmark for one model.
#
#   bench/run.sh <model> [go|design|all|<lang>,...] [repeats]
#   bench/run.sh mistral-large-3:675b-cloud all 3
#
# Generates config/agents/bench-candidate.yaml from bench/agent-template.yaml,
# runs the bench config(s) review-only, scores each run against the manifest,
# and appends to bench/results.csv. The generated agent file is removed on
# exit. Methodology: bench/README.md.
set -eu

MODEL=${1:?usage: bench/run.sh <model> [go|design|all|<lang>,...] [repeats]}
TASKS=${2:-all}
REPEATS=${3:-1}

cd "$(dirname "$0")/.."
CANDIDATE=config/agents/bench-candidate.yaml
LOCK=bench/.run.lock

# The bench is inherently SERIAL: one generated candidate agent file, one
# results.csv appended to, and one .fixpoint/ to find this run's summary in.
# Two overlapping invocations would clobber each other's model and could
# attribute one run's measurements to the other's model (review run
# 20260813-161029) -- fabricated rows in the file that decides panel seats. So
# concurrency is refused rather than accommodated.
#
# noclobber, not mkdir: Ubuntu 26.04 ships uutils coreutils, whose mkdir is not
# a reliable atomic test-and-set, while `set -C` redirection is POSIX and fails
# if the file exists.
if ! (set -C; echo "$$" >"$LOCK") 2>/dev/null; then
    echo "bench: another benchmark is running (lock $LOCK held by PID $(cat "$LOCK" 2>/dev/null)); the bench is serial by design -- wait for it, or remove the lock if that PID is gone" >&2
    exit 2
fi
trap 'rm -f "$LOCK" "$CANDIDATE"' EXIT

# Refuse to clobber a real agent file; only ever manage our own generated one.
if [ -e "$CANDIDATE" ] && ! grep -q 'generated by bench/run.sh' "$CANDIDATE"; then
    echo "bench: $CANDIDATE exists and was not generated by this script; refusing" >&2
    exit 2
fi

# A baseline (claude, codex) is an EXISTING agent measured through its own
# yaml -- the ollama template would wrap it in the wrong harness. A claude-*
# model id is an Anthropic variant: claude.yaml with only the model swapped
# (effort stays at the production setting, so the model is the one variable).
# Everything else is an ollama model generated from the template.
if [ -f "config/agents/$MODEL.yaml" ]; then
    {
        echo "# generated by bench/run.sh -- do not edit, do not commit"
        cat "config/agents/$MODEL.yaml"
    } >"$CANDIDATE"
elif [ "${MODEL#claude-}" != "$MODEL" ]; then
    {
        echo "# generated by bench/run.sh -- do not edit, do not commit"
        sed "s|^model: .*|model: $MODEL|" config/agents/claude.yaml
    } >"$CANDIDATE"
elif [ "${MODEL#codex@}" != "$MODEL" ]; then
    # codex@<openrouter-id> routes through the CODEX harness instead of the
    # claude one. It exists because the claude harness cannot read some models'
    # replies on this route at all: OpenRouter's Anthropic translation puts a
    # signature-only thinking block AFTER the text for e.g. gemini-3.7-flash,
    # and the harness's result field comes out empty on every call (measured
    # 2026-08-19; grok works there only because its text arrives last). The
    # codex responses-API wire format has no block-order dependence.
    #
    # Same card-billing rules as the claude route below; comparability is
    # against the CODEX baseline, which shares this harness.
    if [ -z "${OPENROUTER_API_KEY:-}" ]; then
        echo "bench: $MODEL is an OpenRouter id but OPENROUTER_API_KEY is not set" >&2
        exit 2
    fi
    {
        echo "# generated by bench/run.sh -- do not edit, do not commit"
        sed "s|__MODEL__|${MODEL#codex@}|" bench/agent-template-openrouter-codex.yaml
    } >"$CANDIDATE"
elif [ "${MODEL#*/}" != "$MODEL" ]; then
    # A slash means an OpenRouter id (x-ai/grok-4.6, moonshotai/...). This
    # route bills a card, and the agent yaml points ANTHROPIC_BASE_URL at
    # openrouter.ai while passing ANTHROPIC_AUTH_TOKEN through -- so the token
    # is ALWAYS overwritten with the OpenRouter key, never merely defaulted.
    # An operator with ANTHROPIC_AUTH_TOKEN already exported (the normal setup
    # for Claude Code against a gateway) would otherwise have sent their
    # Anthropic credential to a third party (review run 20260813-124710).
    if [ -z "${OPENROUTER_API_KEY:-}" ]; then
        echo "bench: $MODEL is an OpenRouter id but OPENROUTER_API_KEY is not set" >&2
        exit 2
    fi
    ANTHROPIC_AUTH_TOKEN=$OPENROUTER_API_KEY
    export ANTHROPIC_AUTH_TOKEN
    # ANTHROPIC_API_KEY takes precedence over the auth token inside the
    # harness, so an exported one would silently bill Anthropic for a model
    # bought elsewhere -- and reach openrouter.ai on the way.
    unset ANTHROPIC_API_KEY
    {
        echo "# generated by bench/run.sh -- do not edit, do not commit"
        sed "s|__MODEL__|$MODEL|" bench/agent-template-openrouter.yaml
    } >"$CANDIDATE"
else
    {
        echo "# generated by bench/run.sh -- do not edit, do not commit"
        sed "s|__MODEL__|$MODEL|" bench/agent-template.yaml
    } >"$CANDIDATE"
    # Record the exact model the tag resolves to right now: floating :cloud
    # tags can be re-pointed between runs, and a measurement of an unknown
    # model is not a measurement (see config/agents/deepseek-ollama.yaml).
    ollama show "$MODEL" 2>/dev/null | sed -n '1,8p' || echo "bench: WARNING: ollama show $MODEL failed" >&2
fi

make build >/dev/null

run_task() {
    task=$1 rep=$2
    # One line per target. Every code-flavoured language shares bench-code.yaml
    # -- the config names the lenses, and -target below points them at a
    # different tree -- so adding a language is an entry here plus a manifest,
    # not a new config. `code` stays as an alias for `go`, which is what every
    # invocation and every row in results.csv meant before the rename.
    case $task in
    go | code) cfg=bench-code   manifest=bench/manifest-go.yaml     target=bench/testdata/target-go ;;
    design)    cfg=bench-design manifest=bench/manifest-design.yaml target=bench/testdata/target-design ;;
    *)
        # A language target added to bench/testdata/target-<name> with a
        # matching bench/manifest-<name>.yaml is runnable with no edit here.
        cfg=bench-code
        manifest=bench/manifest-$task.yaml
        target=bench/testdata/target-$task
        if [ ! -f "$manifest" ] || [ ! -d "$target" ]; then
            echo "bench: unknown task '$task' (no $manifest / $target)" >&2
            return 1
        fi
        ;;
    esac
    echo "bench: $MODEL / $task / repeat $rep"
    # Remember what existed BEFORE this invocation: the summary to score is the
    # one this run created, never merely the newest on disk. Scoring the newest
    # (the first version of this script) silently attributed a previous run's
    # results to the current model whenever startup failed before a summary was
    # written -- fabricated numbers, in the file that decides panel seats
    # (review run 20260813-124710).
    marker=$(mktemp)
    ./fixpoint "$cfg" -target "$target" --trusted-target --trusted-bundle || {
        # exit 4 is review-only's normal termination; anything else is the
        # candidate failing, which the bench records rather than hides.
        code=$?
        if [ "$code" != 4 ]; then
            echo "bench: run exited $code (recorded; a model that cannot finish a run cannot hold a seat)" >&2
        fi
    }
    # With concurrency refused above, a run directory newer than the marker can
    # only be this invocation's.
    rundir=$(ls -dt .fixpoint/*/ 2>/dev/null | while read -r d; do
        [ "$d" -nt "$marker" ] && echo "$d"
    done | head -1)
    rm -f "$marker"
    if [ -z "$rundir" ]; then
        echo "bench: this invocation created no run directory; nothing to score" >&2
        return 1
    fi
    summary=$(ls -t "$rundir"summary-*.json 2>/dev/null | head -1)
    if [ -z "$summary" ]; then
        echo "bench: $rundir has no summary (the run died before writing one); nothing to score" >&2
        return 1
    fi
    python3 bench/score.py "$manifest" "$summary" "$MODEL" "$rep"
}

rep=1
while [ "$rep" -le "$REPEATS" ]; do
    case $TASKS in
    all)
        # `all` is deliberately the CALIBRATED pair, not every target on disk:
        # it is what every published score out of 100 means, and silently
        # widening it as languages are added would change what a comparable
        # run costs and what its total is. Name a language to measure it.
        run_task go "$rep"
        run_task design "$rep"
        ;;
    *)
        # Comma- or space-separated list, so one invocation can sweep several
        # targets: TASK=go,rust,design
        for one in $(echo "$TASKS" | tr ',' ' '); do
            run_task "$one" "$rep"
        done
        ;;
    esac
    rep=$((rep + 1))
done

echo "bench: done -> bench/results.csv"
